services:
  postgres:
    image: postgres:17-alpine
    container_name: shopping-list-db
    environment:
      POSTGRES_DB: shopping_list
      POSTGRES_USER: shopping_user
      POSTGRES_PASSWORD: shopping_password123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: